services:
  router:
    image: ghcr.io/apollographql/router:v0.9.2
    environment:
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
    volumes:
      - ./knighthacks_router/schema.graphql:/etc/config/supergraph.graphql
      - ./knighthacks_router/configuration.yaml:/etc/config/configuration.yaml
    command: [ "-c", "/etc/config/configuration.yaml", "--supergraph", "/etc/config/supergraph.graphql", "--log", "debug" ]
    ports:
      - "4000:4000"
  events:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_events
      dockerfile: ./Dockerfile
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
  users:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_users
      dockerfile: ./Dockerfile
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
  sponsors:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_sponsors
      dockerfile: ./Dockerfile
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
  hackathon:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_hackathon
      dockerfile: ./Dockerfile
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
  postgres:
    image: "postgres:14-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./testing/postgres/init.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: