services:
  router:
    image: ghcr.io/apollographql/router:v0.9.2
    environment:
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
    volumes:
      - ./knighthacks_router/schema.graphql:/etc/config/supergraph.graphql
      - ./knighthacks_router/script.rhai:/etc/config/script.rhai
      - ./knighthacks_router/configuration.yaml:/etc/config/configuration.yaml
    command: [ "-c", "/etc/config/configuration.yaml", "--supergraph", "/etc/config/supergraph.graphql", "--log", "debug" ]
    ports:
      - "4000:4000"
  events:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_events
      dockerfile: ./Dockerfile
    env_file: [ .env ]
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
      DATABASE_URI: "postgresql://postgres:test@postgres:5432/postgres"
  users:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_users
      dockerfile: ./Dockerfile
    env_file: [ .env ]
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
      DATABASE_URI: "postgresql://postgres:test@postgres:5432/postgres"
  sponsors:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_sponsors
      dockerfile: ./Dockerfile
    env_file: [ .env ]
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
      DATABASE_URI: "postgresql://postgres:test@postgres:5432/postgres"
  hackathon:
    depends_on:
      - router
      - postgres
    build:
      context: ./knighthacks_hackathon
      dockerfile: ./Dockerfile
    env_file: [ .env ]
    environment:
      GIN_MODE: "debug"
      TRUSTED_PROXIES: ""
      DATABASE_URI: "postgresql://postgres:test@postgres:5432/postgres"
  postgres:
    image: "postgres:14-alpine"
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./testing/postgres/init.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-logs:/logs:z
volumes:
  postgres-data:
  postgres-logs: